name: spring
main: com.piggest.minecraft.bukkit.spring.Spring
api-version: 1.13
version: 0.0.1
author: Pentyum
commands:
  spring:
    description: place water on your foot.
    usage: /<command> to place water on your foot or /<command> setprice [world] to change price.
    permission: placewater.place
    permission-message: You don't have permission
permissions:
  spring.*:
    description: Gives access to all placewater commands
    default: op
  spring.place:
    description: Gives access to place water
    default: true
  spring.changeprice:
    description: change place water price
    default: op
softdepend: [Vault]