name: spring
main: com.piggest.minecraft.bukkit.spring.Spring
api-version: 1.15
version: 0.2.0
author: Pentyum
commands:
  spring:
    description: Spring plugin 0.2.0
    usage: Spring plugin 0.2.0
    permission: spring.use
    permission-message: You don't have permission
permissions:
  spring.*:
    description: Gives access to all spring commands
    default: op
  spring.use:
    description: Use spring.
    default: true
  spring.changeprice:
    description: change place spring price.
    default: op
softdepend: [Vault]